# Site settings
author: Brandon Weygant
title: Brandon's Coding Journal
header-img: img/home-bg.png
email: bobbydigital108@gmail.com
copyright_name: Brandon Weygant
description: > # this means to ignore newlines until "baseurl:"
  Based On Probably Something Similar To A True Story
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BMWeygant

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
